package ru.myproevent.domain.utils

const val PARTICIPANTS_PICKER_RESULT_KEY = "PARTICIPANTS_PICKER_RESULT"
const val CONTACTS_KEY = "CONTACTS"
const val PARTICIPANT_TO_REMOVE_ID_RESULT_KEY = "PARTICIPANT_TO_REMOVE_ID_RESULT"
const val PARTICIPANT_ID_KEY = "PARTICIPANT_ID"