package ru.myproevent.ui.presenters.events.event.participant_pickers.participant_by_email_picker

import moxy.viewstate.strategy.alias.AddToEndSingle
import ru.myproevent.ui.presenters.events.event.participant_pickers.ParticipantsPickerView

@AddToEndSingle
interface ParticipantByEmailPickerView : ParticipantsPickerView